version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: gavarnie-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gavarnie_core
    ports:
      - '13306:3306'
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-proot']
      interval: 5s
      timeout: 3s
      retries: 20

  mongo:
    image: mongo:6
    container_name: gavarnie-mongo
    ports:
      - '27018:27017'

  redis:
    image: redis:7
    container_name: gavarnie-redis
    ports:
      - '16379:6379'

  minio:
    image: minio/minio:latest
    container_name: gavarnie-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - '19000:9000' # S3 API
      - '19001:9001' # 콘솔 UI
    volumes:
      - minio-data:/data

  mc:
    image: minio/mc:latest
    container_name: gavarnie-mc
    depends_on:
      - minio
    entrypoint: ['/bin/sh', '/config/setup.sh']
    volumes:
      - ./minio/setup.sh:/config/setup.sh:ro

  nginx:
    image: nginx:1.25
    container_name: gavarnie-nginx
    depends_on:
      - minio
    ports:
      - '18080:80' # HLS 프록시(개발용)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  minio-data:
